name: Integration specs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare postgres database
      run: RAILS_ENV=test docker-compose run web rails db:create db:migrate
    - name: Run integration specs
      run: docker-compose up --build test
